### PR TITLE
Rename script2.py to preprocess_data.py

### PR DESCRIPTION
**Pull request by GloriaWYY**
- Incorporate the `.map(str)` change.
- I comment out the preprocessing code for ML, because I guess these should be moved to the ML script (Reasoning: please see the script, basically we were not outputting preprocessor)
- After reviewing, we can delete the comments to make this script cleaner.
- I tested this preprocess_data.py from the command line, it worked and eda.py also worked with the input train_df.csv generated from this preprocess_data.py

### CODE REVIEW

**Comment by paradise1260** [comment]
@GloriaWYY 
I believe based on Milestone 2 instructions the preprocessing needs to be done in this script. I did not get why you commented out the preprocessing section. I transformed the data using the preprocessor and then returned the train and test dataframes as csv files.

**Comment by GloriaWYY** [comment]
@paradise1260 
Oh I suggest this because the output file from this script should also be
the input file for EDA. Remember that in EDA we summarize features and plot
graphs on feature values, with this transformed train_df we are summarizing
the scaled values, which I think shouldn’t be the case? So what I was
suggesting is to keep the pure data frames and do the preprocessing in the
ML script.

Does this explanation make sense? If not, we can discuss more during
meeting.

**Comment by paradise1260** [comment]
@GloriaWYY 
I guess we can take the raw data as the input for EDA. The instruction does not specify that the output of script 2 has to be the input of the script3. But it explicitly says that script 2 needs to include preprocessing. 
And yes, we can discuss that in the meeting today.

**Comment by Luming-ubc** [comment]
I did not go through the entire script yet. But, based on your previous discussions, I think what Paniz did make sense to me, because the outputs from the second script should be the input for both third script - EAD, and the fourth script - ML. So, it makes sense to me to do the preprocessing in the second script. However, as Gloria pointed out, the issue would be the input for third script - EDA. To solve that, we could use second script to output multiple processed data, meaning inputs for 3rd script and 4th script separately.

**Comment by GloriaWYY** [comment]
@paradise1260 YES, I agree, I can update eda.py which should do the same data split as in this script. 
@Luming-ubc It is also a solution. We can discuss which approach we want during meeting.

**Comment by paradise1260** [comment]
@GloriaWYY 
Thank you Gloria! It is much better now. Just a quick fix. Could you please update the Usage at the beginning to src/preprocess_data.py?

**Comment by GloriaWYY** [comment]
> @GloriaWYY Thank you Gloria! It is much better now. Just a quick fix. Could you please update the Usage at the beginning to src/preprocess_data.py?

@paradise1260 You meant updating the Usage section in README? Sure, I can do that, but I guess Gabe will put all command lines there after we finish up all scripts. @gfairbro Do you want me to update Usage as we are working?

**Comment by gfairbro** [comment]
Leave usage to me at the end, for the most part. I think it will be easier to just do some testing and tweak that way.  I will just edit that one path directly in the README if it is wrong

**Comment by gfairbro** [comment]
I think @paradise1260 was referring to the usage in the documentation of the script itself which looks to be changed now. I will merge this request.

**Comment by paradise1260** [comment]
Yes, I was referring to that. Don't worry I will fix it. It seems it is not changed.

**Pull request merged**
